server:
  port: 9090

spring:
  cloud:
    gateway:
      default-filters:
        -TokenRelay
      routes:
        - id: proxy
          predicates:
              - Path=/**
          uri: http://localhost:8086

security:
  oauth2:
    client:
      provider:
        keycloak-test:
          issuer-uri: http://localhost:8080/realms/el-aparato-melissa-bonilla
      registration:
        keycloak-test:
          authorization-grant-type: authorization_code
          client-id: api-gateway-client
          client-secret: WOIX1ugMWFiUd44fR0QwtV3ZXjV10RZn
          redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
          scope:
            - openid